import './globals.css';
import type { Metadata } from 'next';
import { Merriweather_Sans } from 'next/font/google';
import Header from './components/Header';
import Footer from './components/Footer';
import PageLayout from './components/layouts/PageLayout';

const merriweather_sans = Merriweather_Sans({
  subsets: ['latin', 'cyrillic-ext'],
  variable: '--font-merriweather_sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={merriweather_sans.className}>
        <PageLayout>
          <Header />
          {children}
          <Footer />
        </PageLayout>
      </body>
    </html>
  );
}
